# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ad8f59e8836154045b4dbb4f46a315414732c920b73c2a7981dca8b6995dc698577f3c1c5f5813234b32afa4cfe464df5fc6840f61a1b82cc15c2e9eab3201f

test:
  secret_key_base: 31666a92a7cf208d4626b2d2ad4b7e24bfab777ac4530cb89ec4b3b31633b150a71d62afb1282087b3bd6a524844bbcadd906177c0be56c6229681bc6032db4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
